### ISSUE TITLE
UAV get stuck after running a short time when launch the Quick Start demo

### ISSUE THREAD

**Issue by BingyangZHOU** [SYSU-STAR/RACER#2]
Thanks for wonderful work!
I run RACER in ubuntu 18.04
I follow the guide,and run  "source devel/setup.bash && roslaunch exploration_manager swarm_exploration.launch".
After click the "2D Nav Goal" in Gazebo, two of four uavs start to move. But after about 1 second, all UAVs got stuck as follows:

![Screenshot from 2023-02-24 21-54-27](https://user-images.githubusercontent.com/60862795/221197819-bc451590-00b8-4450-93c8-e0b85951510e.png)

and I got the error log in terminal as follows (everything goes well when I run FUEL demo in my pc):

Stack trace (most recent call last):
#4    Object "", at 0xffffffffffffffff, in 
#3    Object "/home/young8/multi_exploration/Racer_ws/devel/lib/libpath_searching.so", at 0x7f80dd0b400a, in fast_planner::KinodynamicAstar::cubic(double, double, double, double) [clone .cold.1153]
#2    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7f80db41fd06, in _Unwind_Resume
#1    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7f80db41f3e5, in 
#0    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7f80db41ef34, in 
Segmentation fault (Signal sent by the kernel [(nil)])
[ WARN] [1677247602.391850051]: Pair opt 1 & 3
[ERROR] [1677247602.414712002]: Larger cost after reallocation
[ WARN] [1677247602.414811365]: Drone 1 send opt request to 3, pair opt t: 0.022999, allocate t: 0.020624
[ WARN] [1677247602.417611228]: get response 1
[ WARN] [1677247602.491863740]: Pair opt 1 & 4
[ WARN] [1677247602.507779446]: Replan: cluster covered=====================================
[ WARN] [1677247602.515244865]: Drone 1 send opt request to 4, pair opt t: 0.023395, allocate t: 0.020891
[ WARN] [1677247602.516000740]: Replan: cluster covered=====================================
[ WARN] [1677247602.533452422]: get response 1
[ WARN] [1677247602.537027062]: Replan: cluster covered=====================================
Stack trace (most recent call last):
#4    Object "", at 0xffffffffffffffff, in 
#3    Object "/home/young8/multi_exploration/Racer_ws/devel/lib/libpath_searching.so", at 0x7fbdc825000a, in fast_planner::KinodynamicAstar::cubic(double, double, double, double) [clone .cold.1153]
#2    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7fbdc65bbd06, in _Unwind_Resume
#1    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7fbdc65bb3e5, in 
#0    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7fbdc65baf34, in 
Segmentation fault (Signal sent by the kernel [(nil)])
[exploration_node_2-9] process has died [pid 18736, exit code -11, cmd /home/young8/multi_exploration/Racer_ws/devel/lib/exploration_manager/exploration_node /odom_world:=/state_ukf/odom_2 /map_ros/pose:=/pcl_render_node/sensor_pose_2 /map_ros/depth:=/pcl_render_node/depth_2 /map_ros/cloud:=/pcl_render_node/cloud_2 /planning/replan:=/planning/replan_2 /planning/new:=/planning/new_2 /planning/bspline:=/planning/bspline_2 /swarm_expl/drone_state_send:=/swarm_expl/drone_state /swarm_expl/drone_state_recv:=/swarm_expl/drone_state /swarm_expl/pair_opt_send:=/swarm_expl/pair_opt /swarm_expl/pair_opt_recv:=/swarm_expl/pair_opt /swarm_expl/pair_opt_res_send:=/swarm_expl/pair_opt_res /swarm_expl/pair_opt_res_recv:=/swarm_expl/pair_opt_res /swarm_expl/grid_tour_send:=/swarm_expl/grid_tour /swarm_expl/hgrid_send:=/swarm_expl/hgrid /multi_map_manager/chunk_stamps_send:=/multi_map_manager/chunk_stamps /multi_map_manager/chunk_data_send:=/multi_map_manager/chunk_data /multi_map_manager/chunk_stamps_recv:=/multi_map_manager/chunk_stamps /multi_map_manager/chunk_data_recv:=/multi_map_manager/chunk_data /planning/swarm_traj_recv:=/planning/swarm_traj /planning/swarm_traj_send:=/planning/swarm_traj /planning_vis/trajectory:=/planning_vis/trajectory_2 /planning_vis/frontier:=/planning_vis/frontier_2 /planning_vis/viewpoints:=/planning_vis/viewpoints_2 /sdf_map/occupancy_all:=/sdf_map/occupancy_all_2 /sdf_map/occupancy_local:=/sdf_map/occupancy_local_2 /sdf_map/occupancy_local_inflate:=/sdf_map/occupancy_local_inflate_2 /sdf_map/unknown:=/sdf_map/unknown_2 /sdf_map/update_range:=/sdf_map/update_range_2 /sdf_map/basecoor:=/swarm_sim_tf/basecoor_2 __name:=exploration_node_2 __log:=/home/young8/.ros/log/5feaccee-b44c-11ed-a4bd-38002590fcd6/exploration_node_2-9.log].
log file: /home/young8/.ros/log/5feaccee-b44c-11ed-a4bd-38002590fcd6/exploration_node_2-9*.log
[exploration_node_1-2] process has died [pid 18701, exit code -11, cmd /home/young8/multi_exploration/Racer_ws/devel/lib/exploration_manager/exploration_node /odom_world:=/state_ukf/odom_1 /map_ros/pose:=/pcl_render_node/sensor_pose_1 /map_ros/depth:=/pcl_render_node/depth_1 /map_ros/cloud:=/pcl_render_node/cloud_1 /planning/replan:=/planning/replan_1 /planning/new:=/planning/new_1 /planning/bspline:=/planning/bspline_1 /swarm_expl/drone_state_send:=/swarm_expl/drone_state /swarm_expl/drone_state_recv:=/swarm_expl/drone_state /swarm_expl/pair_opt_send:=/swarm_expl/pair_opt /swarm_expl/pair_opt_recv:=/swarm_expl/pair_opt /swarm_expl/pair_opt_res_send:=/swarm_expl/pair_opt_res /swarm_expl/pair_opt_res_recv:=/swarm_expl/pair_opt_res /swarm_expl/grid_tour_send:=/swarm_expl/grid_tour /swarm_expl/hgrid_send:=/swarm_expl/hgrid /multi_map_manager/chunk_stamps_send:=/multi_map_manager/chunk_stamps /multi_map_manager/chunk_data_send:=/multi_map_manager/chunk_data /multi_map_manager/chunk_stamps_recv:=/multi_map_manager/chunk_stamps /multi_map_manager/chunk_data_recv:=/multi_map_manager/chunk_data /planning/swarm_traj_recv:=/planning/swarm_traj /planning/swarm_traj_send:=/planning/swarm_traj /planning_vis/trajectory:=/planning_vis/trajectory_1 /planning_vis/frontier:=/planning_vis/frontier_1 /planning_vis/viewpoints:=/planning_vis/viewpoints_1 /sdf_map/occupancy_all:=/sdf_map/occupancy_all_1 /sdf_map/occupancy_local:=/sdf_map/occupancy_local_1 /sdf_map/occupancy_local_inflate:=/sdf_map/occupancy_local_inflate_1 /sdf_map/unknown:=/sdf_map/unknown_1 /sdf_map/update_range:=/sdf_map/update_range_1 /sdf_map/basecoor:=/swarm_sim_tf/basecoor_1 __name:=exploration_node_1 __log:=/home/young8/.ros/log/5feaccee-b44c-11ed-a4bd-38002590fcd6/exploration_node_1-2.log].
log file: /home/young8/.ros/log/5feaccee-b44c-11ed-a4bd-38002590fcd6/exploration_node_1-2*.log
[ WARN] [1677247602.821016119]: Pair opt 3 & 4
[ WARN] [1677247602.834322157]: Drone 3 send opt request to 4, pair opt t: 0.013321, allocate t: 0.012186
[ WARN] [1677247602.834615143]: get response 1
[ WARN] [1677247602.893309530]: Drone 3, [1.000550,0.344042,0.343853,3.832224], [time, length, vel, energy]
[ WARN] [1677247602.898017805]: Drone 4, [0.999200,0.213831,0.214002,2.681881], [time, length, vel, energy]
[ WARN] [1677247602.898866902]: Drone 2, [0.769890,0.082941,0.107731,5.035449], [time, length, vel, energy]
[ WARN] [1677247602.927753537]: Replan: cluster covered=====================================
[ WARN] [1677247602.937479053]: Drone 1, [0.924734,0.093479,0.101088,2.852091], [time, length, vel, energy]
[ WARN] [1677247602.943360037]: Replan: cluster covered=====================================
[ WARN] [1677247603.347882201]: Replan: cluster covered=====================================
[ WARN] [1677247603.353065950]: Replan: cluster covered=====================================
Stack trace (most recent call last):
#4    Object "", at 0xffffffffffffffff, in 
#3    Object "/home/young8/multi_exploration/Racer_ws/devel/lib/libpath_searching.so", at 0x7faf0a55800a, in fast_planner::KinodynamicAstar::cubic(double, double, double, double) [clone .cold.1153]
#2    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7faf088c3d06, in _Unwind_Resume
#1    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7faf088c33e5, in 
#0    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7faf088c2f34, in 
Segmentation fault (Signal sent by the kernel [(nil)])
[exploration_node_3-16] process has died [pid 18799, exit code -11, cmd /home/young8/multi_exploration/Racer_ws/devel/lib/exploration_manager/exploration_node /odom_world:=/state_ukf/odom_3 /map_ros/pose:=/pcl_render_node/sensor_pose_3 /map_ros/depth:=/pcl_render_node/depth_3 /map_ros/cloud:=/pcl_render_node/cloud_3 /planning/replan:=/planning/replan_3 /planning/new:=/planning/new_3 /planning/bspline:=/planning/bspline_3 /swarm_expl/drone_state_send:=/swarm_expl/drone_state /swarm_expl/drone_state_recv:=/swarm_expl/drone_state /swarm_expl/pair_opt_send:=/swarm_expl/pair_opt /swarm_expl/pair_opt_recv:=/swarm_expl/pair_opt /swarm_expl/pair_opt_res_send:=/swarm_expl/pair_opt_res /swarm_expl/pair_opt_res_recv:=/swarm_expl/pair_opt_res /swarm_expl/grid_tour_send:=/swarm_expl/grid_tour /swarm_expl/hgrid_send:=/swarm_expl/hgrid /multi_map_manager/chunk_stamps_send:=/multi_map_manager/chunk_stamps /multi_map_manager/chunk_data_send:=/multi_map_manager/chunk_data /multi_map_manager/chunk_stamps_recv:=/multi_map_manager/chunk_stamps /multi_map_manager/chunk_data_recv:=/multi_map_manager/chunk_data /planning/swarm_traj_recv:=/planning/swarm_traj /planning/swarm_traj_send:=/planning/swarm_traj /planning_vis/trajectory:=/planning_vis/trajectory_3 /planning_vis/frontier:=/planning_vis/frontier_3 /planning_vis/viewpoints:=/planning_vis/viewpoints_3 /sdf_map/occupancy_all:=/sdf_map/occupancy_all_3 /sdf_map/occupancy_local:=/sdf_map/occupancy_local_3 /sdf_map/occupancy_local_inflate:=/sdf_map/occupancy_local_inflate_3 /sdf_map/unknown:=/sdf_map/unknown_3 /sdf_map/update_range:=/sdf_map/update_range_3 /sdf_map/basecoor:=/swarm_sim_tf/basecoor_3 __name:=exploration_node_3 __log:=/home/young8/.ros/log/5feaccee-b44c-11ed-a4bd-38002590fcd6/exploration_node_3-16.log].
log file: /home/young8/.ros/log/5feaccee-b44c-11ed-a4bd-38002590fcd6/exploration_node_3-16*.log
[ WARN] [1677247603.773967676]: Replan: cluster covered=====================================
[ WARN] [1677247603.898132827]: Drone 4, [1.999318,0.988353,0.494345,5.149499], [time, length, vel, energy]
[ WARN] [1677247603.898965140]: Drone 2, [0.769890,0.082941,0.107731,5.035449], [time, length, vel, energy]
[ WARN] [1677247603.901671420]: Drone 3, [1.790637,1.070052,0.597582,17.157516], [time, length, vel, energy]
[ WARN] [1677247603.937533827]: Drone 1, [0.924734,0.093479,0.101088,2.852091], [time, length, vel, energy]
[ WARN] [1677247604.186434847]: Replan: cluster covered=====================================
[ WARN] [1677247604.648216646]: Replan: cluster covered=====================================
[ WARN] [1677247604.908088316]: Drone 4, [3.009233,1.775520,0.590024,12.785846], [time, length, vel, energy]
[ WARN] [1677247604.908892480]: Drone 2, [0.769890,0.082941,0.107731,5.035449], [time, length, vel, energy]
[ WARN] [1677247604.911605524]: Drone 3, [1.790637,1.070052,0.597582,17.157516], [time, length, vel, energy]
[ WARN] [1677247604.939140315]: Drone 1, [0.924734,0.093479,0.101088,2.852091], [time, length, vel, energy]
[ WARN] [1677247605.059736308]: Replan: cluster covered=====================================
[ WARN] [1677247605.475253547]: Replan: cluster covered=====================================

**Comment by ZbyLGsc** [comment]
please check the latest code, we just fixed this issue

**Comment by BingyangZHOU** [comment]
I update the code and try again. Now everything goes well.
Thanks ^^

> please check the latest code, we just fixed this issue

**Comment by Qhijane** [comment]
> please check the latest code, we just fixed this issue

hello, Prof. Zhou. when I running this code: source devel/setup.bash && roslaunch exploration_manager swarm_exploration.launch. I have facing a problem that confuse me, why its occur this error:"[ERROR] [1711975484.051144093]: Larger cost after reallocation
[ERROR] [1711975484.051167210]: Path 1 inconsistent"... the result as following picture below. Why is the final result different from the author's? Is the result I obtained also correct? If not correct, which files should be modified? Thank you very much and I look forward to your reply. Thank you.
![2024-04-06 18-06-30屏幕截图](https://github.com/SYSU-STAR/RACER/assets/154677141/9d64b0f5-38bf-4248-b73f-157bb40c6888)
