### ISSUE TITLE
catkin_make后提示缺少lkh_mtsp_solver/SolveMTSP.h

### ISSUE THREAD

**Issue by LYQBOY** [SYSU-STAR/RACER#26]
在执行完catkin_make之后报了这样的错误：
```
......
Scanning dependencies of target mtsp_node
[ 29%] Building CXX object RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/src2/mtsp_node.cpp.o
/home/yang/catkin_ws/src/RACER/swarm_exploration/utils/lkh_mtsp_solver/src2/mtsp_node.cpp:6:10: fatal error: lkh_mtsp_solver/SolveMTSP.h: No such file or directory
 #include <lkh_mtsp_solver/SolveMTSP.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/build.make:3710: recipe for target 'RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/src2/mtsp_node.cpp.o' failed
make[2]: *** [RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/src2/mtsp_node.cpp.o] Error 1
CMakeFiles/Makefile2:2549: recipe for target 'RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/all' failed
make[1]: *** [RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j1 -l1" failed
```
我应该怎么修改呢？
还有一点是：在报错之后，我运行这行命令1仍是可以启动的；
`1 source devel/setup.bash && roslaunch exploration_manager rviz.launch`
但是运行这行命令2
`2 source devel/setup.bash && roslaunch exploration_manager swarm_exploration.launch`
会报以下错误
```
ERROR: cannot launch node of type [map_generator/map_pub]: Cannot locate node of type [map_pub] in package [map_generator]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [exploration_manager/exploration_node]: Cannot locate node of type [exploration_node] in package [exploration_manager]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [lkh_mtsp_solver/mtsp_node]: Cannot locate node of type [mtsp_node] in package [lkh_mtsp_solver]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [lkh_mtsp_solver/mtsp_node]: Cannot locate node of type [mtsp_node] in package [lkh_mtsp_solver]. Make sure file exists in package path and permission is set to executable (chmod +x)
.......
No processes to monitor
shutting down processing monitor...
... shutting down processing monitor complete
```
大概20个左右ERROR: cannot launch node of type

**Comment by yangwenguanggit** [comment]
me too，解决问题了吗？请指教

**Comment by Zager-Zhang** [comment]
现在的代码应该已经修复了这个问题。
之前是因为编译用的cpu核心数太少了（`make -j1 -l1`），现在修复了这个问题，用任何数量的cpu核心编译都应该没有问题了

**Comment by Hewiex** [comment]
> 现在的代码应该已经修复了这个问题。 之前是因为编译用的cpu核心数太少了（`make -j1 -l1`），现在修复了这个问题，用任何数量的cpu核心编译都应该没有问题了

我也遇到了这个问题。。。
@Zager-Zhang 

/home/hewie/Desktop/RACER/src/RACER/swarm_exploration/utils/lkh_mtsp_solver/src2/mtsp_node.cpp:6:10: fatal error: lkh_mtsp_solver/SolveMTSP.h: No such file or directory
    6 | #include <lkh_mtsp_solver/SolveMTSP.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/build.make:2039: RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/src2/mtsp_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2740: RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j2 -l2" failed

**Comment by Hewiex** [comment]
> > 现在的代码应该已经修复了这个问题。 之前是因为编译用的cpu核心数太少了（`make -j1 -l1`），现在修复了这个问题，用任何数量的cpu核心编译都应该没有问题了
> 
> 我也遇到了这个问题。。。 @Zager-Zhang
> 
> /home/hewie/Desktop/RACER/src/RACER/swarm_exploration/utils/lkh_mtsp_solver/src2/mtsp_node.cpp:6:10: fatal error: lkh_mtsp_solver/SolveMTSP.h: No such file or directory 6 | #include <lkh_mtsp_solver/SolveMTSP.h> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. make[2]: *** [RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/build.make:2039: RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/src2/mtsp_node.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:2740: RACER/swarm_exploration/utils/lkh_mtsp_solver/CMakeFiles/mtsp_node.dir/all] Error 2 make: *** [Makefile:141: all] Error 2 Invoking "make -j2 -l2" failed



对于这个问题，更改了虚拟机的核心数后，似乎得到了解决。

**Comment by Zeying-Gong** [comment]
我在复现另一个仓库 [ApexNav](https://github.com/Robotics-STAR-Lab/ApexNav) 的时候也遇到这个问题，排查之后发现问题根因在ApexNav/src/planner/utils/lkh_mtsp_solver/CMakeLists.txt需要在最后一行target_link_libraries(tsp_node ...) 之前添加这一行：
```
add_dependencies(tsp_node ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
```

这样 tsp_node 就会等待 SolveMTSP.h 生成后再编译。修改核心数可能是通过并行处理然后提前把这个头文件生成了。
