### ISSUE TITLE
Compile error: fatal error: plan_env/ChunkStamps.h: No such file or directory

### ISSUE THREAD

**Issue by yonggaogit** [SYSU-STAR/RACER#3]
When I compile the source code with `catkin_make`, I get the error: in multi_map_manager.h:7:10: fatal error: plan_env/ChunkStamps.h: There are no such files or directories. I checked in the source code that I really didn't find this file under the plan_env folder.

**Comment by ZbyLGsc** [comment]
read readme carefully

**Comment by yonggaogit** [comment]
> read readme carefully

Sorry for my negligence

**Comment by MGC-ly** [comment]
I tried to recompile the project with catkin_make and still got this error

**Comment by Brynn-pl** [comment]
> > read readme carefully
> 
> Sorry for my negligence

I encountered the same issue as you, so would you mind sharing the solution with me?

**Comment by Brynn-pl** [comment]
> I tried to recompile the project with catkin_make and still got this error

So did I,so did you solve the problem ,and would  you mind sharing the solution with me?

**Comment by MGC-ly** [comment]
> > I tried to recompile the project with catkin_make and still got this error
> 
> So did I,so did you solve the problem ,and would you mind sharing the solution with me?

I solved the problem by adding the following line in all CMakelists.txt files:
set(CMAKE_CXX_STANDARD 14)

**Comment by yonggaogit** [comment]
Yes，First check the "Known issues" chapter on RADME.md，and recompile the code

**Comment by Mr-Zhao-lin** [comment]
it still occured after adding set(CMAKE_CXX_STANDARD 14) and recompile.
probably because the sequence of files generate when compile.
Finally this issue solved by catkin_make -j4
